# Generated by Django 4.2.13 on 2024-06-11 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backgroundcode', '0003_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'ordering': ['email'],
            },
        ),
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-created_on']},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['user']},
        ),
    ]
